### ISSUE TITLE
Что нам нужно на сайте?

### ISSUE THREAD

**Issue by langovoi** [krddevdays/frontend#54]
- События
- Доклады
- Подача заявок на выступление
- Вакансии и резюме
- Фото

**Comment by binakot** [comment]
К каждому событию можно приурочить соответствующий логотип. Timepad, вроде, не поддерживает логотип мероприятия. Но по ключевому слову в названии (backend, frontend, python, etc) мы можем подставлять соотвествующий тег и логотип в заголовке. Визуально будет проще ориентироваться в матрице событий.

Также хорошей идеей считаю добавить фильтр по видам мероприятий: krddevdays, backend, frontend, python, etc. Зашел на сайт, открыл только backend ивенты и радуешься ☕️

**Comment by langovoi** [comment]
> К каждому событию можно приурочить соответствующий логотип. Timepad, вроде, не поддерживает логотип мероприятия. Но по ключевому слову в названии (backend, frontend, python, etc) мы можем подставлять соотвествующий тег и логотип в заголовке. Визуально будет проще ориентироваться в матрице событий.

Пока хотелка на будущее (без нормально дизайнера хз что делать).

> Также хорошей идеей считаю добавить фильтр по видам мероприятий: krddevdays, backend, frontend, python, etc. Зашел на сайт, открыл только backend ивенты и радуешься ☕️

Завел задачу: #56

> Также круто было бы добавить список спикеров и рядом прямые ссылки на видеозаписи их выступлений на youtube.

С этим пока сложности, пока у нас не будет собственной базы - не сделать.

**Comment by vladimirdotk** [comment]
Может быть цитатник из чатов

**Comment by binakot** [comment]
Было бы прикольно потом прикрутить телеграмм и собирать какую-нибудь статистику и топы. Типа самый активный, самый многословный, самый постящий картинки :D

**Comment by neonick** [comment]
Ну и вообще, ссылки на все каналы. Хотя думаю, это в планах уже.

**Comment by neonick** [comment]
Для прошедших митапов и конф добавить статистику, фоточки, публикации(?), плейлист с ютуба.

**Comment by langovoi** [comment]
> Ну и вообще, ссылки на все каналы. Хотя думаю, это в планах уже.

#65

**Comment by langovoi** [comment]
> Для прошедших митапов и конф добавить статистику, фоточки, публикации(?), плейлист с ютуба.

Какие публикации ты имеешь ввиду?
А вообще подобное мы пока не сделаем без #59

**Comment by neonick** [comment]
`Какие публикации ты имеешь ввиду?`
Ну СМИ там, Хабр(?), такое :)

**Comment by LovelySnowman** [comment]
Прежде, чем пилить безумные фичи, вроде публикации постов с телеграма на сайте, надо наполнить содержимым сайт. Уже увидел связь #65, но вконтакте, как мне кажется, информации маловато.

- Какая цель создания сообщества? Марк хочет мир захватывать через сообщество, как я понял. Может, подумать над формулировкой? 
- Мы привязаны к локации Краснодар? Сообщество создается федерального уровня или планетарного? Нет задачи объединить разработчиков Краснодара, прежде всего?

Поштормим:
- Подумать над целями и задачами сообщества
- Карточки мероприятий
  - Лого мероприятия (вроде, есть для Backend и Frontend) (@binakot писал об этом уже)
  - Цель мероприятия
  - Формат (написать, что после митапов обычно афтерпати собираются)
  - Кто проводит
  - Где обычно проводится
  - Календарь мероприятия
- Карточки организаторов
  - Имя
  - Опыт работы (это не для того, чтобы выпендриваться, просто человек, возможно, на конференцию специально приедет с кем-то из вас пообщаться по теме вашей работы, вы же фронтлайнеры)
  - Контакты
- Общий календарь событий с выходом на карточки мероприятий (лого мероприятий в календаре)
- Ссылки на ресурсы/контакты: чаты, ютуб, соц. сети (упоминалось @neonick)

P.S.
- Да, я зарегался специально, чтобы покомментировать Issue:)
- Резюме я бы отложил в долгий ящик: вы сообщество или рекрутинговое агенство?
- Я думаю, надо в приоритете календарь запилить и карточки оргов, после этого уже можно продумать следующие вехи.

**Comment by langovoi** [comment]
@LovelySnowman спасибо за длиннопост, очень полезно и по делу 👍 

> Прежде, чем пилить безумные фичи, вроде публикации постов с телеграма на сайте, надо наполнить содержимым сайт.

Собственно этот тикет и нужен, чтобы собрать различные мнения, пожелания, а потом приоритизировать.
