### ISSUE TITLE
Пропал символ рубля

### ISSUE THREAD

**Issue by binakot** [krddevdays/frontend#58]
opera58 win7

![image](https://user-images.githubusercontent.com/1783893/53291897-6c842880-37cb-11e9-9584-d378a98c52f4.png)

**Comment by langovoi** [comment]
Сейчас используется дефолтный системный шрифт.
Скорее всего проблема с ним в Windows 7.

Надо подумать какие пути решения есть.

**Comment by neonick** [comment]
Предлагаю забить: знак рубля в Win7 решается патчем 5-летней давности.

**Comment by langovoi** [comment]
> знак рубля в Win7 решается патчем 5-летней давности.

Пусть пока висит открытая задача, на всякий, вдруг не единичный случай.
