### ISSUE TITLE
База данных

### ISSUE THREAD

**Issue by langovoi** [krddevdays/frontend#59]
Сейчас мы подтягиваем события с TimePad, но это не есть хорошо.
А помимо продажи билетов у нас есть куча вещей: расписание, доклады и докладчики, фото, участники и всякое такое. 

Хочется поднять свою базу, хранить все у себя.

**Comment by langovoi** [comment]
Для начала стоит завести сущность события, по аналогии с TimePad.

Событие в TimePad должно создаваться вызовом API от нашего сервера.
Должна быть синхронизация, так как в TimePad событие могут редактироваться (но стремимся к тому, что такого не было).

**Comment by langovoi** [comment]
Для начала нужно создать сущность юзера с системой разграничением доступа, сделать логин, регистрацию и восстановление данных.

**Comment by binakot** [comment]
Есть какие-то предпочтения по стеку?

**Comment by langovoi** [comment]
> Есть какие-то предпочтения по стеку?

База: Postgres

А вот что в Node.js использовать для нее - даже не знаю.

**Comment by binakot** [comment]
@wilixlead что посоветуешь для работы с PostgreSQL с NodeJS?

**Comment by langovoi** [comment]
Тут вообще нужно по другому вопрос ставить. Нам нужно сейчас систему пользователей и CMS какую-нибудь прикрутить и работать с CMS через API, чтобы на сайте отображать всякое и пользователей регистрироваться и авторизовывать.

**Comment by binakot** [comment]
> Для начала нужно создать сущность юзера с системой разграничением доступа, сделать логин, регистрацию и восстановление данных. Предусмотреть на будущее систему входа через OAuth провайдеры (ВК, Facebook, Telegram).
> 
> E-mail считаем обязательным, их может быть несколько.
> 
> После этого у нас будут развязаны руки, чтобы сделать централизованную админку + личный кабинет.

Что значит несколько e-mail? Один главный, остальные запасные? В чем смысл и профит?

**Comment by langovoi** [comment]
> Что значит несколько e-mail? Один главный, остальные запасные? В чем смысл и профит?

У нас есть люди, которые покупают на 3-4 разных e-mail билеты. Хочет чтобы они могли это внутри одного аккаунта держать.

**Comment by binakot** [comment]
> Тут вообще нужно по другому вопрос ставить. Нам нужно сейчас систему пользователей и CMS какую-нибудь прикрутить и работать с CMS через API, чтобы на сайте отображать всякое и пользователей регистрироваться и авторизовывать.

Back office / админка по сути? Дергает тот же API только с другими ролями и разрешениями.

**Comment by WilixLead** [comment]
> @WilixLead что посоветуешь для работы с PostgreSQL из NodeJS?
Лично я любитель sequelize, хотя последнее время народ смотрит в сторону knex.js

**Comment by langovoi** [comment]
> Back office / админка по сути?
Ага, все так.

**Comment by binakot** [comment]
Ну я на NodeJS/TS писать вообще не мастак. С PostgreSQL, схемой и обслуживанием помогу.

**Comment by langovoi** [comment]
Для работы с пользователями из нашего фронтенда (сайта и его сервера), думал использовать [next-auth](https://github.com/iaincollins/next-auth). Эта штука агностик к тому, откуда данные юзера.

**Comment by DenisLebedinsky** [comment]
Я в своём учебном проекте как раз разбираюсь с Node + Postgres ,  и как раз недавно сделал вроде годную авторизацию через Google. https://github.com/DenisLebedinsky/trello-server 
Так что в принципе могу помочь)

**Comment by langovoi** [comment]
@DenisLebedinsky спасибо за интерес, но у нас [бекенд](https://github.com/krddevdays/backend) на Django
