### ISSUE TITLE
Ивент пропадает с главной страницы в день мероприятия

### ISSUE THREAD

**Issue by binakot** [krddevdays/frontend#87]
У нас конфа 24-25 августа, начиная с утра 25 августа ивент считается прошедшим. И пропадает с главном страницы.

**Comment by langovoi** [comment]
Кажется нужно поправить фильтрацию в запросе на клиенте.

**Comment by langovoi** [comment]
Closed in #97

**Comment by binakot** [comment]
Блин, а я сижу пытаюсь воспроизвести.

```
const from = new Date();
from.setDate(from.getDate() - 1);
const to = new Date();
to.setDate(to.getDate());
events.forEach(e => {
    e.start_date = from.toISOString();
    e.finish_date = to.toISOString();
});
```

Не воспроизводится, значит пофикшено :)
