### ISSUE TITLE
Поправить выпадающие списки

### ISSUE THREAD

**Issue by Rheola** [krddevdays/frontend#90]
![изображение](https://user-images.githubusercontent.com/6149367/65414258-019bde00-ddfc-11e9-938a-23c8471e2056.png)

Если только 1 вариант выбора - скрыть его?

**Comment by Rheola** [comment]
аналогично на странице оплаты - выбор варианта - только банковской картой? Зачем?

**Comment by langovoi** [comment]
На конференции был мульты-выбор, собственно пока так и осталось. Обязательно улучшим UX в этом месте

**Comment by Rheola** [comment]
Это понятно: если есть выбор, то выпадающий список, если нет - то вообще скрывать или ставить по умолчанию.
