### ISSUE TITLE
Валидация номера телефона

### ISSUE THREAD

**Issue by Rheola** [krddevdays/frontend#91]
Ввожу 
79181234567 

типа невалидный
Попробуй догадайся, что именно не так.

**Comment by langovoi** [comment]
Номер нужно указать в международном формате +7XXXXXXXXXX. Постараемся улучшить информативность ошибок.

@krddevdays/site-backend а можно сделать ошибку более информативной?

**Comment by Rheola** [comment]
Вот по мне так, чтобы не мучить пользоватлеля. Указал без +7 или просто 8 - пусть backend  приводит их в нужный вид
