### ISSUE TITLE
Нет кнопки выхода из профиля

### ISSUE THREAD

**Issue by binakot** [krddevdays/frontend#93]
Нет возможности выйти из профиля, чтобы перезайти или еще что....

**Comment by langovoi** [comment]
А зачем она нужна?

**Comment by binakot** [comment]
Ну вот просто так. Как минимум, выходить. Ты же на всех сайтах видишь кнопку log out? :D

**Comment by langovoi** [comment]
Ну нам не нужно такая кнопка, пока что точно.

**Comment by binakot** [comment]
@langovoi как выйти из системы? Я думаю, что такая функциональность должна быть. Вдруг парень с девушкой (или любые другие гендеры) живут вместе и ходят к нам на ивенты. И с одного компа, но с разных акков зарегались. Как им перезайти? Анонимная вкладка, разные браузеры?
