### ISSUE TITLE
Форма предложения мероприятия вместо 500 ISE

### ISSUE THREAD

**Issue by shsmad** [krddevdays/frontend#96]
**Описание текущей ситуации:**

При запросе страницы несуществующего мероприятия (например, https://krd.dev/events/666) сервер отвечает 500 Internal Server Error.

**Предложение:**

При запросе страницы несуществующего мероприятия отображать форму для предложения тематики нового мероприятия.

**Comment by binakot** [comment]
Нужно научить бэкэнд отчечать 204 NO CONTENT на обращение к событиям, которых не существует. А фронтенд на такой ответ просто редиректит на главную страницу сайта.

**Comment by binakot** [comment]
Отлично. Сейчас на странице `https://krd.dev/events/100500` отображается 
<img width="378" alt="Снимок экрана 2020-01-05 в 21 41 16" src="https://user-images.githubusercontent.com/1783893/71784384-1cd5d680-3004-11ea-9107-44e82fd5e842.png">

Так оставим или сделаем редирект на главную страницу сайта?

**Comment by langovoi** [comment]
Редирект - странно.
Надо в дальнейшем сделать реально что-то вроде формы или выводить список мероприятий («по ссылке ничего нет, но вот есть другие мероприятия»)

**Comment by binakot** [comment]
Вынесем в отдельную таску? Или это оставим открытой?
